apiVersion: v1
kind: Service
metadata:
  name: devops-lab-service
  labels:
    app: devops-lab-app
spec:
  type: NodePort
  selector:
    app: devops-lab-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
      nodePort: 30080
