apiVersion: v1
kind: Service
metadata:
  name: devops-lab-service
spec:
  selector:
    app: devops-lab-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
