# jenkins/kubeconfig.template.yaml
apiVersion: v1
kind: Config

clusters:
- name: k3d-dev-cluster
  cluster:
    server: https://<K3D_API_ENDPOINT>
    certificate-authority-data: <BASE64_CA_CERT>

contexts:
- name: k3d-dev-cluster
  context:
    cluster: k3d-dev-cluster
    user: jenkins-user

current-context: k3d-dev-cluster

users:
- name: jenkins-user
  user:
    client-certificate-data: <BASE64_CLIENT_CERT>
    client-key-data: <BASE64_CLIENT_KEY>
